### ISSUE TITLE
Looks like there might be an issue with coder-review command

### ISSUE THREAD

**Issue by nate-rcl** [Islandora-Labs/islandora_vagrant#119]
1.  Cloned islandora_vagrant: git clone https://github.com/islandora-labs/islandora_vagrant
2. vagrant up
3. vagrant ssh
4. cd /var/www/drupal/
5. drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora

Got the following error:

`WD php: PHP_CodeSniffer_Exception: Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found in include_once() (line 13 of  [error]
/var/www/drupal/sites/all/modules/coder/coder_sniffer/Drupal/Sniffs/Commenting/FileCommentSniff.php).
Cannot modify header information - headers already sent by (output started at /usr/share/php/drush/includes/output.inc:37)         [warning]
bootstrap.inc:1232
PHP_CodeSniffer_Exception: Class PHP_CodeSniffer_CommentParser_ClassCommentParser not found in include_once() (line 13 of /var/www/drupal/sites/all/modules/coder/coder_sniffer/Drupal/Sniffs/Commenting/FileCommentSniff.php).
Drush command terminated abnormally due to an unrecoverable error.   `

**Comment by lutaylor** [comment]
I have successfully replicated this and tried upgrading PHP codesniffer which got rid of the error but a new one appeared. I have another box that I don't have this problem but I had it locked at an older version of codesniffer

Thinking we could try changing 

https://github.com/Islandora-Labs/islandora_vagrant_base_box/blob/master/scripts/devtools.sh#L54

To something like
pear install PHP_CodeSniffer-1.5.6

Then after we test cut a new basebox. 

@DonRichards 
Unless you have any other ideas?

**Comment by DonRichards** [comment]
Did you check 1.5.6 works? You can do a PR with the change and I'll test it.

**Comment by lutaylor** [comment]
I have it working on another box and I tried cutting new test box but seems to be having issues with the version of coder we are using. Any idea why we are using coder 8.x vs 7.x?

**Comment by DonRichards** [comment]
Possibly because its newer. That's a good reason right ;-)

**Comment by lutaylor** [comment]
I suppose so. Going to keep poking at this ideally working with newer versions.

**Comment by lutaylor** [comment]
Seems that the issue is this https://github.com/lutaylor/islandora_vagrant_base_box/blob/master/scripts/devtools.sh#L55-L63 is conflicting with https://github.com/lutaylor/islandora_vagrant_base_box/blob/master/scripts/drupal.sh#L114-L115

Now I can make it work if I remove the coder-8.x bit and install PHP_CodeSniffer 1.5.7 (due to this https://www.drupal.org/node/2387871)  and leave the coder 7.x stuff. If we remove the coder 8.x stuff you loose out on the tests you can run with phpcs however.  
e.g.
`phpcs --standard=Drupal /var/www/drupal/sites/all/modules/islandora`

The coder-review command that you are running doesn't seem to work at all with the 8.x stuff. 

@DonRichards 
Just wondering what direction we should take here.

**Comment by DonRichards** [comment]
I like it. You should put in a PR with that change and I'll take a look.

**Comment by lutaylor** [comment]
https://github.com/Islandora-Labs/islandora_vagrant_base_box/pull/25
